### ISSUE TITLE
Does Not Recognize Common Indexes For PFObject

### ISSUE THREAD

**Issue by ZacharyKhan** [Frugghi/SwiftLCS#2]
For some reason `SwiftLCS` does not recognize the two collections as containing common indexes. The two arrays being compared are exactly the same, but `SwiftLCS` removes all indexes and adds them back instead of simply recognizing that they are common indexes. 

I essentially have a query that pulls all data, and I have SwiftLCS compare the cached data array to the new, in-coming data array.

**Comment by Frugghi** [comment]
Can you share a demo project to reproduce the issue?

I suspect that the issue might be with the implementation of `Equatable` of your data objects.

**Comment by ZacharyKhan** [comment]
Sure, would a code snippet suffice or would you like me to upload a repo with the reproducible problem in a project?

The two arrays being compared are arrays containing `PFObject`'s. More info on this in Parse's blog/documentation.

**Comment by Frugghi** [comment]
I believe that [PFObject](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/PFObject.m) doesn't override `isEqual:` so it's using the [NSObject](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/ObjectComparison.html) default implementation that do pointer comparison.

When you download the newer data you have new objects with different pointers so `SwiftLCS` thinks that you're removing all the items and adding new items. To use `SwiftLCS` with Objective-C classes you should override `isEqual:` and `hashCode` (see [Objective-C Equality](http://nshipster.com/equality/)).

I'm closing the issue, feel free to reopen it if you find out this is not the correct solution.

**Comment by ZacharyKhan** [comment]
Okay, thank you for the info - I will look into it and follow up if the issue stems from something else.

**Comment by ZacharyKhan** [comment]
Fixed by added the following extension to `PFObject` for future reference..

```swift
extension PFObject {
    
    open override func isEqual(_ object: Any?) -> Bool {
      
        if (object as? PFObject)?.objectId == self.objectId {
            return true
        } else {
            return false
        }
    }
    
}
```
