### ISSUE TITLE
Crash when the length is a bit long

### ISSUE THREAD

**Issue by alirezadavoodi** [Frugghi/SwiftLCS#3]
Whenever the length of the text is a bit long (about 510 characters) the algorithm crashes in the following function:

and this line: else if table[i][j] == table[i][j-1] 

  /// Walks back through the generated table to generate the diff.
    fileprivate static func diffFromIndices(_ table: [[Int]], _ x: [Element], _ y: [Element], _ i: Int, _ j: Int) -> Diff<Element> {
        
        
        if i == 0 && j == 0 {
            return Diff<Element>(results: [])
        } else if i == 0 {
            return diffFromIndices(table, x, y, i, j-1) + DiffStep.insert(j-1, y[j-1])
        } else if j == 0 {
            return diffFromIndices(table, x, y, i - 1, j) + DiffStep.delete(i-1, x[i-1])
        } else if table[i][j] == table[i][j-1] {
            return diffFromIndices(table, x, y, i, j-1) + DiffStep.insert(j-1, y[j-1])
        } else if table[i][j] == table[i-1][j] {
            return diffFromIndices(table, x, y, i - 1, j) + DiffStep.delete(i-1, x[i-1])
        } else {
            return diffFromIndices(table, x, y, i-1, j-1)
        }
   
    }

**Comment by Frugghi** [comment]
I didn't test the implementation with large inputs. If you can provide me a demo project that reproduces the crash I can work on some optimizations.

**Comment by alirezadavoodi** [comment]
sure thanks. I will do it.
