### ISSUE TITLE
Compiler warning in Xcode 9 GM with Swift 3.2 project

### ISSUE THREAD

**Issue by ghost** [Frugghi/SwiftLCS#6]
SwiftLCS.swift line 116: Conditional downcast from 'Self.Element?' to 'Self.Element' does nothing

It's relating to this downcast:
`while let lhs = entry.0 as? Iterator.Element,`

**Comment by Frugghi** [comment]
Fixed, thanks! Do you need a new Cocoapods release?

**Comment by ghost** [comment]
Yes, please. Thank you for this and for fixing it.

**Comment by Frugghi** [comment]
@ghowen sorry for the delay! I've published version `1.2.0` on Cocoapods, you can use that with Xcode 9 and Swift 4.

**Comment by ghost** [comment]
No worries. Thanks. Works like a charm.
